update UpdateVersion.yaml again

diff --git a/.github/workflows/UpdateVersion.yaml b/.github/workflows/UpdateVersion.yaml
--- a/.github/workflows/UpdateVersion.yaml
+++ b/.github/workflows/UpdateVersion.yaml
@@ -26,7 +26,6 @@ jobs:
         run:    |
                 $( git describe --tags --abbrev=0) -match 'mkrel-(.+)' > $null
                 $tag = $matches[1]
-                if ( "$tag" -eq "" ) { echo "FAILED TO GET TAG" ; exit 1 }
                 $tag -cmatch '(?<MAJOR>\d+?)\.(?<MINOR>\d+?)\.(?<PATCH>\d+?)(?<EXTRA>.*)' > $null
                 $tag_3_part = $Matches.MAJOR + '.' + $Matches.MINOR + '.' + $Matches.PATCH
                 $copyright = "Copyright © 2022-$((Get-Date).Year) by `$`(Authors`)"
@@ -35,6 +34,9 @@ jobs:
 
                 echo "tag=$tag" >> "$GITHUB_OUTPUT"
                 if ("$tag" -eq "") { exit 1 }
+
+      - name:   Validate Output
+        run:    if ( "${{ steps.update-version.outputs.tag }}" -eq "" ) { echo "FAILED TO SET OUTPUT TO A VALID TAG NAME!" ; exit 1 }
 
       - name:   Push Changes
         run:    |
@@ -45,10 +47,10 @@ jobs:
                 git push origin
 
       - name:   Create & Push Tag
-        uses:   actions-ecosystem/action-push-tag@v1.0.0
-        with:
-          tag: "${{ steps.update-version.outputs.tag }}"
-          message: "Tag for version ${{ steps.update-version.outputs.tag }} generated by the UpdateVersion.yaml workflow"
+        run:    |
+                $tag = "${{ steps.update-version.outputs.tag }}"
+                git tag $tag
+                git push origin $tag
 
       - name:   "Repo Dispatch 'make-release'"
         uses:   peter-evans/repository-dispatch@v2.1.2
