what is github actions' problem?

diff --git a/.github/workflows/UpdateVersion.yaml b/.github/workflows/UpdateVersion.yaml
--- a/.github/workflows/UpdateVersion.yaml
+++ b/.github/workflows/UpdateVersion.yaml
@@ -22,7 +22,7 @@ jobs:
           fetch-depth:  0
 
       - name:   Update .csproj Version Numbers
-        id:     update_version
+        id:     setversion
         run:    |
                 $( git describe --tags --abbrev=0) -match 'mkrel-(.+)' > $null
                 $tag = $matches[1]
@@ -33,10 +33,9 @@ jobs:
                 .\.github\workflows\scripts\SetProperty.ps1  -Path WpfExporter/WpfExporter.csproj  "Version=$tag"  "FileVersion=$tag_3_part"  "Copyright=$copyright"
 
                 echo "tag=$tag" >> "$GITHUB_OUTPUT"
-                if ("$tag" -eq "") { exit 1 }
 
       - name:   Validate Output
-        run:    if ( "${{ steps.update_version.outputs.tag }}" -eq "" ) { echo "FAILED TO SET OUTPUT TO A VALID TAG NAME!" ; exit 1 }
+        run:    if ( "${{ steps.setversion.outputs.tag }}" -eq "" ) { echo "FAILED TO SET OUTPUT TO A VALID TAG NAME!" ; exit 1 }
 
       - name:   Push Changes
         run:    |
@@ -48,7 +47,7 @@ jobs:
 
       - name:   Create & Push Tag
         run:    |
-                $tag = "${{ steps.update_version.outputs.tag }}"
+                $tag = "${{ steps.setversion.outputs.tag }}"
                 git tag $tag
                 git push origin $tag
 
@@ -59,7 +58,7 @@ jobs:
           client-payload: |-
             {
               "ref": "${{ github.ref }}",
-              "tag": "${{ steps.update_version.outputs.tag }}"
+              "tag": "${{ steps.setversion.outputs.tag }}"
             }
         
 # HEAD:github-actions
