update UpdateVersion.yaml

diff --git a/.github/workflows/UpdateVersion.yaml b/.github/workflows/UpdateVersion.yaml
--- a/.github/workflows/UpdateVersion.yaml
+++ b/.github/workflows/UpdateVersion.yaml
@@ -31,7 +31,11 @@ jobs:
                 
                 .\.github\workflows\scripts\SetProperty.ps1  -Path WpfExporter/WpfExporter.csproj  "Version=$tag"  "FileVersion=$tag_3_part"  "Copyright=$copyright"
 
-                echo "tag=$tag" >> $GITHUB_OUTPUT
+                echo "tag=$tag" >> "$GITHUB_OUTPUT"
+                if ($tag -eq "") { exit 1 }
+
+      - name:   Ensure new tag was created
+        run:    if ( ${{ steps.update-version.outputs.tag }} -eq "" ) { echo "Failed to create a valid tag!" ; exit 1 }
 
       - name:   Push Changes
         run:    |
@@ -41,10 +45,11 @@ jobs:
                 git commit -m "Update .csproj Version Numbers"
                 git push origin
 
-                # Create & push release tag for the new commit
-                $tag = ${{ steps.update-version.outputs.tag }}
-                git tag $tag
-                git push origin $tag
+      - name:   Create & Push Tag
+        uses:   actions-ecosystem/action-push-tag@v1.0.0
+        with:
+          tag: "${{ steps.update-version.outputs.tag }}"
+          message: "Tag for version ${{ steps.update-version.outputs.tag }} generated by the UpdateVersion.yaml workflow"
 
       - name:   "Repo Dispatch 'make-release'"
         uses:   peter-evans/repository-dispatch@v2.1.2
